runtime: python313
entrypoint: hypercorn -b :$PORT main:app
# 0.5 vCPU 512Mb
instance_class: F2

automatic_scaling:
  max_instances: 4

env_variables:
  CHANNEL_ID: "-1002527071196"  # https://t.me/+gPR4vB9kL8M4MTg6
  CHAT_ID: "-1002527071195"
  ADMIN_IDS: "75291100"  # @mittov
  WEBHOOK_URL: "https://memebot-459222.ey.r.appspot.com/webhook"
  TELEGRAM_TOKEN: projects/719240642737/secrets/telegram_token/versions/latest
  GERMAN_NEWS_CX_KEY: projects/719240642737/secrets/german_news_cx_key/versions/latest
  SEARCH_API_KEY: projects/719240642737/secrets/search_api_key/versions/latest
  MODEL_NAME: "vertex_ai/gemini-2.5-pro"
  LOG_LEVEL: "INFO"
  EXPLAIN_TOPIC: "projects/memebot-459222/topics/explain"
  EXPLAIN_SUBSCRIPTION: "projects/memebot-459222/subscriptions/sub-explain-pull"

service_account: memebot-459222@appspot.gserviceaccount.com
# ─── URL routing ──────────────────────────────────────────────────────────────

handlers:
  - url: /webhook
    script: auto

  - url: /pubsub/.*
    script: auto

  - url: /.*
    script: auto
