runtime: python312
entrypoint: gunicorn -b :$PORT main:app
# 0.5 vCPU 512Mb
instance_class: F2

env_variables:
  CHANNEL_ID: "-1002527071196"  # https://t.me/+gPR4vB9kL8M4MTg6
  ADMIN_IDS: "75291100"  # @mittov
  WEBHOOK_URL: "https://memebot-459222.ey.r.appspot.com/webhook"
  TELEGRAM_TOKEN: projects/719240642737/secrets/telegram_token/versions/latest
  MODEL_NAME: "gemini-2.0-flash"

service_account: memebot-459222@appspot.gserviceaccount.com
# ─── URL routing ──────────────────────────────────────────────────────────────

handlers:
  - url: /webhook
    script: auto

  - url: /.*
    script: auto
